datacollector_app/urls.py
from django.urls import path
from .views import List_data_view, Add_expenditure_view, clear_expenditure_table

app_name = 'dca'

urlpatterns = [
    path('', List_data_view.as_view(), name='datacollector-home'),
    path('add_expenditure/', Add_expenditure_view.as_view(), name='data-exp-add'),
    path('clear_table/', clear_expenditure_table, name="clear-expenditure"),
]

datastore/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from userauth.views import User_register_view, delete_account

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('datacollector_app.urls')),
    path('register/', User_register_view.as_view(), name='datastore-register'),
    path('login/', auth_views.LoginView.as_view(template_name='userauth/login.html'), name='datastore-login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='userauth/logout.html'),
         name='datastore-logout'),
    path('delete/', delete_account, name='datastore-user-delete')
]

datacollector_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# creating expenditure models
class Expenditure_data(models.Model):
    date = models.DateField()
    what_for = models.CharField(max_length=100)
    amount = models.DecimalField(max_digits=1000, decimal_places=2)
    owener = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return(f'What for?: {self.what_for}')

    def get_absolute_url(self):
        return(reverse('dca:datacollector-home'))

userauth/models.py
from django.db import models

userauth/forms.py
from django import forms
from django.contrib.auth.models import User


class User_register_form(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password_repeat = forms.CharField(widget=forms.PasswordInput)
    username = forms.CharField()
    email = forms.CharField(widget=forms.EmailInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

    def clean(self):
        cleaned_data = super(User_register_form, self).clean()
        password = cleaned_data['password']
        conf_password = cleaned_data['password_repeat']
        if password == conf_password:
            return(cleaned_data)

datacollector_app/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, CreateView, UpdateView
from .models import Expenditure_data
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages


# creating home view
class List_data_view(LoginRequiredMixin, ListView):  # list.html
    model = Expenditure_data
    template_name = 'datacollector_app/list.html'
    context_object_name = 'exp_data'

    def get_queryset(self):
        return(Expenditure_data.objects.filter(owener=self.request.user))

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['user'] = self.request.user
        data['messages'] = messages.get_messages(self.request)
        data['sum'] = amount_sum(self.request.user)
        return(data)


# add values to the database-Expenditure_data
class Add_expenditure_view(LoginRequiredMixin, CreateView):  # expenditure_data_form.html
    model = Expenditure_data
    fields = ['date', 'what_for', 'amount']

    def form_valid(self, form):
        form.instance.owener = self.request.user
        messages.success(self.request, 'Expenditure data updated successfully.')
        return(super().form_valid(form))


# clear done values from todo_list
@login_required
def clear_expenditure_table(request):
    if request.method == 'POST':
        exp = Expenditure_data.objects.filter(owener=request.user)
        exp.delete()
        messages.success(request, 'Expenditure Table cleared successfully.')
        return(redirect('dca:datacollector-home'))
    return(render(request, 'datacollector_app/list.html'))

def amount_sum(user):
    sum = 0
    exp = Expenditure_data.objects.filter(owener=user)
    for val in exp:
        sum += val.amount
    return(sum)

userauth/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib.auth.models import User
from .forms import User_register_form
from django.contrib import messages


class User_register_view(View):
    template_name = 'userauth/register.html'
    form_class = User_register_form
    model = User

    def get(self, request):
        form = self.form_class(None)
        return(render(request, self.template_name, {'form': form}))

    def post(self, request):
        form = self.form_class(request.POST)
        person = self.model()
        if form.is_valid():
            person.username = form.instance.username
            person.email = form.instance.email
            person.set_password(form.instance.password)
            person.save()
            messages.success(self.request, 'Account Created successfully. You can login now.')
            return(redirect('datastore-login'))
        else:
            return(render(request, self.template_name, {'form': self.form_class(None)}))


# delete account
def delete_account(request):
    if request.method == 'POST':
        user = User.objects.filter(username=request.user.username)
        user.delete()
        return(redirect('datastore-register'))
    else:
        return(render(request, 'userauth/delete_account.html'))

datacollector_app/templates/datacollector_app/expenditure_data_form.html
{% extends 'datacollector_app/head.html' %}
{% block title %}
    Add Expenditure
{% endblock title %}

{% block content %}
<div class="container">
    <form action="" method="post">
        {% csrf_token %}
        {% for x in form %}
        <div class="form-group">
             {{ x.label }}:
             <br />
             {{ x }}
             <br />
         </div>
        {% endfor %}
        <button type="submit" class='btn btn-success'>Add Expenditure</button>
    </form>
</div>
{% endblock content %}

datacollector_app/templates/datacollector_app/head.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock title %}</title>
        <link type="text/css" rel="stylesheet" href="{% static 'datacollector_app/bootstrap.min.css' %}" >
    </head>
    <body>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
            <span class='navbar-brand'>{{ user }}'s App</span>
            <ul class='navbar-nav ml-auto'>
                <li class='nav-item'><a href="{% url 'dca:datacollector-home' %}" class='nav-link'>Home</a></li>
                <li class='nav-item'><a href="{% url 'dca:data-exp-add' %}" class='nav-link'>Update Expenditure</a></li>
                <li class='nav-item'><a href="{% url 'datastore-user-delete' %}" class='nav-link'>Delete Account</a></li>
                <li class='nav-item'><a href="{% url 'datastore-logout' %}" class='nav-link'>Logout</a></li>
            </ul>
        </nav>
        <br />
            {% if messages %}
                {% for message in messages %}
                    <div class='container alert alert-{{ message.tags}}'>{{ message }}</div>
                {% endfor %}
            {% endif %}
            <br />
    <div class = 'container-fluid'>
        {% block content %}
        {% endblock content %}
    </div>
    </body>
</html>

datacollector_app/templates/datacollector_app/list.html
{% extends 'datacollector_app/head.html' %}
{% block title %}
    Datacollector Home
{% endblock title %}

{% block content %}
<div class='container'>
    <h1>Hello {{ user }},</h1>
</div>
<div class="container">
    Total Expenditure till now : {{ sum }}
</div>
<br />
<br />
<div class='container'>
<div class='row'>
    <div class='col-md-12'>
        <h3>Expenditure Table</h3>
        {% if exp_data %}
        <form action="{% url 'dca:clear-expenditure' %}" method="post">
            {% csrf_token %}
            <table class='table'>
                <tr>
                    <th>Date</th>
                    <th>What For?</th>
                    <th>Amount</th>
                </tr>
                {% for exp in exp_data %}
                    <tr>
                        <td>{{ exp.date }}</td>
                        <td>{{ exp.what_for }}</td>
                        <td>{{ exp.amount }}</td>
                    </tr>
                {% endfor %}
            </table>
            <button type='submit' class='btn btn-warning'>Clear Table</button>
        </form>
        {% else %}
            <div>No expenditure data added</div>
        {% endif %}
    </div>
</div>
</div>
{% endblock content %}

userauth/templates/userauth/delete_account.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Delete Account</title>
        <link type="text/css" rel="stylesheet" href="{% static 'datacollector_app/bootstrap.min.css' %}" >
    </head>
    <body>
        <form method="post">
            {% csrf_token %}
            <div class='container'>
                <div class='alert alert-danger'>Are you sure that you want to delete your account?</div>
            <button type="submit" class='btn btn-danger'>Yes</button>
            <a href="{% url 'dca:datacollector-home' %}" class='btn btn-success'>No</a>
            </div>
        </form>
    </body>
</html>

userauth/templates/userauth/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Login</title>
        <link type="text/css" rel="stylesheet" href="{% static 'datacollector_app/bootstrap.min.css' %}" >
    </head>
    <body>
        <div>
            {% if messages %}
                {% for message in messages %}
                <div class='container-fluid alert alert-success'>
                    <strong>{{ message }}</strong>
                </div>
                {% endfor %}
            {% endif %}
        </div>
        <div class="container">
            <fieldset>
        <legend>
            Login Form
        </legend>
        <form method="post">
            {% csrf_token %}
            {% for x in form %}
                <div class='form-group'>
                    {{ x.label }}
                    <br />
                    {{ x }}
                    <br />
                </div>
            {% endfor %}
            <button type="submit" class='btn btn-secondary'>Login</button>
        </div>
        </form>
    </fieldset>
    <br />
            <div class='container'>
                Donot have an account? Then <strong><a href='{% url 'datastore-register' %}' class='btn btn-primary'>Register</a>
            </div>
    </body>
</html>

userauth/templates/userauth/logout.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Logout</title>
        <link type="text/css" rel="stylesheet" href="{% static 'datacollector_app/bootstrap.min.css' %}" >
    </head>
    <body>
        <div class='container'>
            <h1 class='alert alert-primary'>You have Successfully Logged Out.</h1>
            <a href="{% url 'datastore-login' %}" class='btn btn-secondary'>Login Again</a>
        </div>
    </body>
</html>

userauth/templates/userauth/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Register</title>
        <link type="text/css" rel="stylesheet" href="{% static 'datacollector_app/bootstrap.min.css' %}" >
    </head>
    <body>
        <div class='container'>
            <br />
            <br />
        <fieldset>
            <legend>
                Registration Form
            </legend>
        <form method="post">
            {% csrf_token %}
                {% for x in form %}
                    {{ x.label }}
                    <br />
                    {{ x }}
                    <br />
                    {% if x.errors %}
                        {% for error in errors %}
                            <div class='container-fluid alert alert-danger'>
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% endif %}
                    <br />
                {% endfor %}
            <button type="submit" class='btn btn-primary'>Register</button>
        </div>
    </form>
</fieldset>
<br />
            <div class='container'>
                Already have an account? Then <a href='{% url 'datastore-login'%}' class='btn btn-secondary'> Login</a>
            </div>
    </body>
</html>